# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 11:51
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_dashboard.enums.BiogasPlant
import django_dashboard.enums.BiogasPlantContact
import django_dashboard.enums.JobHistory
import django_dashboard.enums.UserDetail
import enumfields.fields
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BiogasPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('funding_souce', models.CharField(blank=True, max_length=225, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=20, null=True)),
                ('other_address_details', models.TextField(blank=True, null=True)),
                ('type_biogas', enumfields.fields.EnumField(enum=django_dashboard.enums.BiogasPlant.TypeBiogas, max_length=1, null=True)),
                ('size_biogas', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Biogas Plant',
                'verbose_name_plural': 'Biogas Plants',
                'permissions': (('remove_biogas', 'Remove a biogas plant from the platform'), ('create_biogas', 'Add a biogas plant to the platform'), ('edit_biogas', 'Edit a biogas plant profile'), ('edit_location_biogas', 'Able to edit a location associated with a biogas plant')),
            },
        ),
        migrations.CreateModel(
            name='BiogasPlantContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('contact_type', enumfields.fields.EnumField(enum=django_dashboard.enums.BiogasPlantContact.ContactType, max_length=1)),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=200, null=True, validators=[django.core.validators.EmailValidator])),
            ],
            options={
                'verbose_name': 'Biogas Plant Owner',
                'verbose_name_plural': 'Biogas Plant Owners',
                'permissions': (('remove_user', 'Remove a user from the platform'), ('create_user', 'Add a user to the platform'), ('edit_user', "Edit a user's profile"), ('edit_mobile_number', 'Able to Edit a users mobile number')),
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=20, null=True)),
                ('other_address_details', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15, null=True)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None)),
                ('other_info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': "Company's",
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('plants', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('faults', models.IntegerField(blank=True, null=True)),
                ('avtime', models.IntegerField(blank=True, null=True)),
                ('jobs', models.IntegerField(blank=True, null=True)),
                ('fixed', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.Company')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard Data',
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_flagged', models.DateTimeField(null=True)),
                ('due_date', models.DateTimeField(null=True)),
                ('date_completed', models.DateTimeField(null=True)),
                ('completed', models.NullBooleanField(db_index=True, default=False)),
                ('job_status', enumfields.fields.EnumField(enum=django_dashboard.enums.JobHistory.JobStatus, max_length=1, null=True)),
                ('fault_description', models.TextField(null=True)),
                ('other', models.TextField(null=True)),
                ('client_feedback_star', models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('client_feedback_additional', models.TextField(null=True)),
                ('overdue_for_acceptance', models.NullBooleanField(default=False)),
                ('priority', models.NullBooleanField(default=False)),
                ('fault_class', models.CharField(blank=True, choices=[('MINOR', 'minor'), ('MAJOR', 'major')], max_length=225, null=True)),
            ],
            options={
                'get_latest_by': ['-priority', '-date_flagged'],
                'verbose_name': 'Job History',
                'verbose_name_plural': 'Job History',
                'permissions': (('remove_job', 'Remove a job from the platform'), ('create_job', 'Add a job to the platform'), ('edit_job', 'Edit a job profile'), ('edit_job_status', 'Able to edit a job status')),
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', enumfields.fields.EnumField(enum=django_dashboard.enums.UserDetail.UserRole, max_length=1, null=True)),
                ('first_name', models.CharField(default=None, editable=False, max_length=200)),
                ('last_name', models.CharField(default=None, editable=False, max_length=200)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('phone_number', models.CharField(db_index=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('neighbourhood', models.CharField(blank=True, max_length=20, null=True)),
                ('other_address_details', models.TextField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('datetime_modified', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'UserDetail',
                'verbose_name_plural': 'UserDetails',
                'permissions': (('remove_user', 'Remove a user from the platform'), ('create_user', 'Add a user to the platform'), ('edit_user', "Edit a user's profile")),
            },
        ),
        migrations.CreateModel(
            name='TechnicianDetail',
            fields=[
                ('technicians', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='django_dashboard.UserDetail')),
                ('technician_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('acredit_to_install', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TUBULAR', 'tubular'), ('FIXED_DOME', 'fixed_dome')], db_index=True, max_length=18, null=True)),
                ('acredited_to_fix', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('TUBULAR', 'tubular'), ('FIXED_DOME', 'fixed_dome')], db_index=True, max_length=18, null=True)),
                ('specialist_skills', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PLUMBER', 'plumber'), ('MASON', 'mason'), ('MANAGER', 'manager'), ('DESIGN', 'design'), ('CALCULATIONS', 'calculations')], db_index=True, max_length=41, null=True)),
                ('number_jobs_active', models.IntegerField(blank=True, null=True)),
                ('number_of_jobs_completed', models.IntegerField(blank=True, null=True)),
                ('status', models.NullBooleanField(choices=[(True, 'Active'), (False, 'Inactive')], db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
                ('average_rating', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('what3words', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Status and Location',
                'verbose_name_plural': 'Status and Location',
                'permissions': (('remove_technician', 'Remove a technician from the platform'), ('create_technician', 'Add a technician to the platform'), ('edit_technician', "Edit a technican's profile")),
            },
        ),
        migrations.AddField(
            model_name='userdetail',
            name='company',
            field=models.ManyToManyField(to='django_dashboard.Company'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='fixers',
            field=models.ManyToManyField(blank=True, to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.BiogasPlant'),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='associated_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.Company'),
        ),
        migrations.AddField(
            model_name='biogasplant',
            name='constructing_technicians',
            field=models.ManyToManyField(blank=True, to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='biogasplant',
            name='contact',
            field=models.ManyToManyField(to='django_dashboard.BiogasPlantContact'),
        ),
    ]
