# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Technition_realtime',
            new_name='TechnitionRealtime',
        ),
    ]
