# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, null=True),
        ),
    ]
