# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0002_auto_20171128_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplants',
            name='funding_souce',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='biogasplants',
            name='status',
            field=models.CharField(blank=True, choices=[('UNDER_CONSTRUCTION', 'under construction'), ('COMMISSIONING', 'commissioning'), ('QP1_operational', 'QP1 operational'), ('QP1_fault', 'QP1 fault'), ('QP2_operational', 'QP2 operational'), ('QP2_fault', 'QP2 fault'), ('OPERATIONAL', 'operational'), ('FAULT', 'fault'), ('DECOMMISSIONED', 'decommissioned')], max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='completed',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='fault_class',
            field=models.CharField(blank=True, choices=[('MINOR', 'minor'), ('MAJOR', 'major')], max_length=225, null=True),
        ),
    ]
