# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-24 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0002_auto_20180824_0729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='role',
        ),
    ]
