# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 18:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0002_auto_20180109_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technitionrealtime',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
    ]
