# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0003_auto_20171206_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
