# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0003_remove_userdetail_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.UserDetail'),
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='volume_biogas',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
