# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0004_auto_20180828_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biogasplant',
            name='volume_biogas',
        ),
    ]
