# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0004_auto_20180116_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdata',
            name='continent',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addressdata',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
