# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-28 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0005_remove_biogasplant_volume_biogas'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='volume_biogas',
            field=models.IntegerField(blank=True, help_text='Integer value indicating the volume of the biogas plant in m3', null=True),
        ),
    ]
