# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0005_auto_20180116_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasplant',
            name='constructing_technicians',
            field=models.ManyToManyField(blank=True, related_name='constructing_technicians', to='django_dashboard.UserDetail'),
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='contact',
            field=models.ManyToManyField(related_name='biogas_plant_detail', to='django_dashboard.BiogasPlantContact'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='date_completed',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='date_flagged',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='techniciandetail',
            name='technicians',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='technician_details', serialize=False, to='django_dashboard.UserDetail'),
        ),
    ]
