# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0006_auto_20180130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='date_flagged',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
