# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-03 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0007_auto_20180903_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='AddressLocation',
        ),
    ]
