# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 09:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0007_auto_20180201_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('message_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('message_from_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True)),
                ('message_to_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True)),
                ('message_from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message_to_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='client_feedback_additional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='client_feedback_star',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='fault_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='related_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.JobHistory'),
        ),
    ]
