# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0009_auto_20180904_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_modified', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='biogasplant',
            name='record_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plant_records_created', to='django_dashboard.UserDetail'),
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plants_adopted', to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='biogasplant',
            name='record_of_edits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plants', to='django_dashboard.EditRecord'),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='record_of_edits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plant_contacts', to='django_dashboard.EditRecord'),
        ),
    ]
