# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-05 09:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0011_auto_20180905_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='editrecord',
            name='previous_model_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
