# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-05 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0012_editrecord_previous_model_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplantcontact',
            name='record_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plant_contact_record_created_by', to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='company',
            name='record_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_record_created_by', to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='company',
            name='record_of_edits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='django_dashboard.EditRecord'),
        ),
        migrations.AddField(
            model_name='pendingjobs',
            name='record_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_job_record_created_by', to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='pendingjobs',
            name='record_of_edits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_job', to='django_dashboard.EditRecord'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='record_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail_record_created_by', to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='record_of_edits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to='django_dashboard.EditRecord'),
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='record_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plant_record_created_by', to='django_dashboard.UserDetail'),
        ),
        migrations.AlterField(
            model_name='biogasplantcontact',
            name='record_of_edits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_plant_contact', to='django_dashboard.EditRecord'),
        ),
    ]
