# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django_dashboard.enums.BiogasPlant
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0012_auto_20180206_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='funding_source_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='funding_souce',
            field=enumfields.fields.EnumField(blank=True, enum=django_dashboard.enums.BiogasPlant.FundingSourceEnum, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='sensor_status',
            field=enumfields.fields.EnumField(blank=True, enum=django_dashboard.enums.BiogasPlant.SensorStatus, max_length=1, null=True),
        ),
    ]
