# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0013_auto_20180206_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='volume_biogas',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
