# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-06 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0013_auto_20180905_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='phone_number',
            new_name='mobile',
        ),
    ]
