# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-06 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0014_auto_20180906_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresslocation',
            name='what3words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
