# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0015_auto_20180206_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biogasplant',
            name='size_biogas',
        ),
    ]
