# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0015_addresslocation_what3words'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
