# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0016_biogasplant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingjobs',
            name='company_of_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_job_creator', to='django_dashboard.UserDetail'),
        ),
    ]
