# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 11:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0016_remove_biogasplant_size_biogas'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='verfied',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='verification_of_engagement',
            field=models.NullBooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='techniciandetail',
            name='rating',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='techniciandetail',
            name='willing_to_travel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
