# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0017_auto_20180207_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='techniciandetail',
            name='max_num_jobs_allowed',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
