# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0017_pendingjobs_company_of_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_abandoning_job', models.TextField(blank=True, null=True)),
                ('technician', models.ManyToManyField(blank=True, related_name='abandonedjob', to='django_dashboard.UserDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='reason_abandoning_job',
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='abandoned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.AbandonedJob'),
        ),
    ]
