# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0018_auto_20180913_1448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbandonedJob',
            new_name='Abandoned',
        ),
    ]
