# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0018_techniciandetail_max_num_jobs_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniciandetail',
            name='rating',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='UserPhotos'),
        ),
    ]
