# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0019_auto_20180208_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='admin_role_in_companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='admin_role_in', to='django_dashboard.Company'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='technican_role_in_companies',
            field=models.ManyToManyField(blank=True, null=True, related_name='tech_role_in', to='django_dashboard.Company'),
        ),
    ]
