# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0019_auto_20180913_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingjobs',
            name='link_to_job_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.JobHistory'),
        ),
        migrations.AddField(
            model_name='pendingjobs',
            name='previously_abandoned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
