# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0020_auto_20180913_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhistory',
            name='rejected_job',
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='rejected_jobs',
        ),
    ]
