# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-17 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0021_auto_20180913_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingjobs',
            name='associated_with_company',
            field=models.ManyToManyField(blank=True, related_name='associated_with_company', to='django_dashboard.Company'),
        ),
    ]
