# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0021_auto_20180208_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='admin_role_in_companies',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='technican_role_in_companies',
        ),
    ]
