# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-17 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0022_pendingjobs_associated_with_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='associated_with_company',
            field=models.ManyToManyField(blank=True, related_name='job_history_associated_with_company', to='django_dashboard.Company'),
        ),
        migrations.AlterField(
            model_name='pendingjobs',
            name='associated_with_company',
            field=models.ManyToManyField(blank=True, related_name='pending_job_associated_with_company', to='django_dashboard.Company'),
        ),
    ]
