# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-18 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0023_auto_20180917_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='old_pending_job_id',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=200),
        ),
    ]
