# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-18 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0024_jobhistory_old_pending_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhistory',
            name='old_pending_job_id',
        ),
    ]
