# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-20 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0025_remove_jobhistory_old_pending_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
