# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0025_auto_20180215_0714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhistory',
            old_name='_assistance',
            new_name='assistance',
        ),
        migrations.RenameField(
            model_name='jobhistory',
            old_name='_completed',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='jobhistory',
            old_name='_priority',
            new_name='priority',
        ),
    ]
