# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0026_auto_20180215_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobhistory',
            old_name='completed',
            new_name='completedjob',
        ),
    ]
