# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0028_auto_20180921_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhistory',
            name='additional_notes',
        ),
    ]
