# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0028_auto_20180216_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='UIC',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
