# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-21 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0029_remove_jobhistory_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='rejected_by',
            field=models.ManyToManyField(blank=True, related_name='job_rejected_by', to='django_dashboard.UserDetail'),
        ),
    ]
