# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0030_jobhistory_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasplant',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogasplant', to='django_dashboard.AddressLocation'),
        ),
    ]
