# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0030_biogasplant_associated_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasplant',
            name='associated_company',
            field=models.ManyToManyField(blank=True, related_name='biogas_plant_company', to='django_dashboard.Company'),
        ),
    ]
