# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0031_auto_20180925_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='list_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
