# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 17:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0032_card_list_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='list_data',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None), blank=True, null=True, size=None),
        ),
    ]
