# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0034_auto_20180219_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingjobs',
            name='biogas_plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.BiogasPlant'),
        ),
        migrations.AlterField(
            model_name='pendingjobs',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.UserDetail'),
        ),
    ]
