# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0034_auto_20180926_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list_data',
            new_name='_list_data',
        ),
    ]
