# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0035_auto_20180926_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtemplate',
            name='company',
        ),
        migrations.AddField(
            model_name='cardtemplate',
            name='company',
            field=models.ManyToManyField(blank=True, null=True, to='django_dashboard.Company'),
        ),
    ]
