# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0036_auto_20180927_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtemplate',
            name='company',
            field=models.ManyToManyField(blank=True, to='django_dashboard.Company'),
        ),
    ]
