# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0037_auto_20180220_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingjobs',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=200),
        ),
    ]
