# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0038_auto_20180220_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingjobs',
            name='biogas_plant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='abiogasplant', to='django_dashboard.BiogasPlant'),
        ),
        migrations.AlterField(
            model_name='pendingjobs',
            name='technician',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='atechician', to='django_dashboard.UserDetail'),
        ),
    ]
