# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-21 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0040_auto_20180220_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='biogas_plant_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='accepted_but_did_not_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptednovisit', to='django_dashboard.UserDetail'),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='dispute_raised',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='rejected_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejectedjob', to='django_dashboard.UserDetail'),
        ),
    ]
