# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0041_auto_20180221_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingjobs',
            name='id',
        ),
        migrations.AlterField(
            model_name='pendingjobs',
            name='job_id',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=200, primary_key=True, serialize=False),
        ),
    ]
