# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0043_jobhistory_rejected_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biogasplant',
            name='what3words',
        ),
        migrations.AlterField(
            model_name='biogasplant',
            name='volume_biogas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='accepted_but_did_not_visit',
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='accepted_but_did_not_visit',
            field=models.ManyToManyField(blank=True, null=True, related_name='acceptednovisit', to='django_dashboard.UserDetail'),
        ),
        migrations.RemoveField(
            model_name='jobhistory',
            name='rejected_job',
        ),
        migrations.AddField(
            model_name='jobhistory',
            name='rejected_job',
            field=models.ManyToManyField(blank=True, null=True, related_name='rejectedjob', to='django_dashboard.UserDetail'),
        ),
    ]
