# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0044_auto_20180307_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='accepted_but_did_not_visit',
            field=models.ManyToManyField(blank=True, related_name='acceptednovisit', to='django_dashboard.UserDetail'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='rejected_job',
            field=models.ManyToManyField(blank=True, related_name='rejectedjob', to='django_dashboard.UserDetail'),
        ),
    ]
