# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0045_auto_20180307_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobhistory',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
