# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0046_jobhistory_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobhistory',
            name='comments',
        ),
    ]
