# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-13 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0048_auto_20180312_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobhistory',
            name='fixers',
            field=models.ManyToManyField(blank=True, related_name='fixerss', to='django_dashboard.UserDetail'),
        ),
    ]
