# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0053_auto_20180314_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='company',
            field=models.ManyToManyField(to='django_dashboard.Company'),
        ),
    ]
