# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0054_auto_20180314_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasplantcontact',
            name='associated_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.Company'),
        ),
    ]
