# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0055_auto_20180323_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='what3words',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
