# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0056_biogasplant_what3words'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
