# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_dashboard', '0057_userdetail_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.IntegerField(blank=True, editable=False, null=True)),
                ('expiry_datetime', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
