# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0058_passwordmanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordmanagement',
            name='reset_code',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
