# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0059_auto_20180414_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='location_estimated',
            field=models.NullBooleanField(default=False),
        ),
    ]
