# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0061_auto_20180516_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indictorjointable',
            name='auto_fault',
        ),
        migrations.RemoveField(
            model_name='indictorjointable',
            name='data_connection',
        ),
        migrations.RemoveField(
            model_name='indictorjointable',
            name='low_gas_pressure',
        ),
        migrations.RemoveField(
            model_name='indictorjointable',
            name='sensor_status',
        ),
        migrations.RemoveField(
            model_name='indictorjointable',
            name='trendChangeDetectionPDecrease',
        ),
        migrations.RemoveField(
            model_name='indictorjointable',
            name='trendchangedetectionPIncrease',
        ),
        migrations.RemoveField(
            model_name='indictorjointable',
            name='utilisation_status',
        ),
        migrations.AddField(
            model_name='autofault',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AddField(
            model_name='biogassensorstatus',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AddField(
            model_name='dataconnection',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AddField(
            model_name='lowgaspressure',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AddField(
            model_name='trendchangedetectionpdecrease',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AddField(
            model_name='trendchangedetectionpincrease',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AddField(
            model_name='utilisationstatus',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisationstatus',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
