# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-17 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0062_auto_20180517_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='template_id',
        ),
        migrations.AlterField(
            model_name='autofault',
            name='auto_fault_detection',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='biogassensorstatus',
            name='sensor_status',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='data_connection_with_plant',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lowgaspressure',
            name='low_gas_pressure_status',
            field=models.IntegerField(blank=True, db_index=True, help_text='If 0 gas pressure is low 10 means all is ok, in between is defined by internal logic', null=True),
        ),
        migrations.AlterField(
            model_name='trendchangedetectionpdecrease',
            name='trend_change_detection_pdecrease',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='trendchangedetectionpincrease',
            name='trend_change_detection_pincrease',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisationstatus',
            name='utilisation_status',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
