# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0065_auto_20180518_1230'),
    ]

    operations = [
        
    ]
