# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 16:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0070_auto_20180518_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='position',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userdetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
