# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0073_uictodeviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uictodeviceid',
            name='biogas_plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='UIC_to_Device_id', to='django_dashboard.BiogasPlant'),
        ),
    ]
