# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-24 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0074_auto_20180524_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autofault',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_fault', to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='biogassensorstatus',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biogas_sensor_status', to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='dataconnection',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_connection', to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='lowgaspressure',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_gas_pressure', to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='trendchangedetectionpdecrease',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_detection_p_decrease', to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='trendchangedetectionpincrease',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trend_detection_p_increase', to='django_dashboard.IndictorJoinTable'),
        ),
        migrations.AlterField(
            model_name='utilisationstatus',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='untilisation', to='django_dashboard.IndictorJoinTable'),
        ),
    ]
