# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0076_auto_20180524_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisationstatus',
            name='join_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisation', to='django_dashboard.IndictorJoinTable'),
        ),
    ]
