# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 21:59
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0077_auto_20180528_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('continent', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('village', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('lat_long', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_dashboard.Address'),
        ),
    ]
