# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-30 22:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0079_auto_20180530_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplantcontact',
            name='continent',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='lat_long',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='village',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biogasplantcontact',
            name='ward',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
