# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0080_auto_20180530_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techniciandetail',
            name='technician_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='techniciandetail',
            name='technicians',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_details', to='django_dashboard.UserDetail'),
        ),
    ]
