# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0081_auto_20180606_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='logged_in_as',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logged_in_as', to='django_dashboard.Company'),
        ),
    ]
