# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0082_auto_20180606_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplant',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
