# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0083_biogasplant_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UIC', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('channel', models.IntegerField(blank=True, db_index=True, null=True)),
                ('band', models.IntegerField(blank=True, db_index=True, null=True)),
                ('mode', models.IntegerField(blank=True, db_index=True, null=True)),
                ('nw_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
        ),
    ]
