# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-29 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0084_registerednode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerednode',
            options={'permissions': (('can_register_node', 'has permission to register a new node on the system'),)},
        ),
    ]
