# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0086_pendingaction_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='action_url',
            field=models.CharField(blank=True, db_index=True, max_length=600, null=True),
        ),
    ]
