# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0087_pendingaction_action_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='action_object',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
