# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-01 15:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0088_pendingaction_action_object'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorObjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('biogas_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='django_dashboard.BiogasPlant')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorsTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('template_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type_indicator', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, db_index=True, max_length=400, null=True)),
                ('units', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='WidgetCards')),
                ('created', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='indicatorobjects',
            name='indicator_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_objects', to='django_dashboard.IndicatorsTemplate'),
        ),
    ]
