# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0089_auto_20180801_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingaction',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='pending_actions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='django_dashboard.PendingAction'),
        ),
    ]
