# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0090_auto_20180802_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='pending_actions',
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='django_dashboard.Card'),
        ),
    ]
