# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 11:29
from __future__ import unicode_literals

from django.db import migrations
import django_dashboard.enums.Dashboard
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0091_auto_20180802_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingaction',
            name='alert_type',
            field=enumfields.fields.EnumField(enum=django_dashboard.enums.Dashboard.AlertTypes, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='entity_type',
            field=enumfields.fields.EnumField(enum=django_dashboard.enums.Dashboard.EntityTypes, max_length=2, null=True),
        ),
    ]
