# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-02 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dashboard', '0093_auto_20180802_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorstemplate',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
